Added Cassandra container
observIQ/charts pull request #12
Opened 2023-02-09 16:22 UTC by algchoo

* Added Cassandra container w/ no authentication for remote JMX

2023-02-09 16:30 UTC, schmikei commented on container/cassandra/docker-compose.yaml
> +    ports:
Does this one need to seed `cassandra1` as well? Or does the default of localhost work in this context?

2023-02-13 16:29 UTC, jsirianni requested changes
I think we need a couple tweaks and it will be good to go. This is what is working great for me:

```yaml
          - name: JVM_OPTS
            value: "-Xms1024M -Xmx1024M -XX:MaxPermSize=1024M -XX:MaxHeapSize=1024M"
        resources:
          limits:
            memory: 2G
          requests:
            cpu: "500m"
            memory: 2G

```

2023-02-13 16:29 UTC, jsirianni commented on charts/cassandra/templates/deployment.yaml
> +            cpu: "500m"
I think it is okay to remove the cpu limit to allow the containers to "burst".

2023-02-13 16:29 UTC, jsirianni commented on charts/cassandra/templates/deployment.yaml
> +            value: "-Xms1024M -Xmx2048M -XX:MaxPermSize=2048M -XX:MaxHeapSize=2048M"
I would set min and max equal, and I think 1024 would be ideal to allow for any filesystem caching that might be needed on top of heap allocation.

2023-02-13 18:27 UTC, jsirianni commented on charts/cassandra/templates/deployment.yaml
> +            value: "-Xms1024M -Xmx2048M -XX:MaxPermSize=2048M -XX:MaxHeapSize=2048M"
@algchoo I think we still need this

2023-02-13 18:27 UTC, jsirianni commented on charts/cassandra/templates/deployment.yaml
> +            value: "-Xms1024M -Xmx2048M -XX:MaxPermSize=2048M -XX:MaxHeapSize=2048M"
To clarify, I think heap min and max can be 1GB, with cgroup limit / request set to 2gb. This allows for any filesystem caching / memory requirements required outside of the JVM heap.

2023-02-13 19:02 UTC, jsirianni approved these changes

2023-02-13 19:08 UTC, schmikei approved these changes

2023-02-13 19:09 UTC, merged