Added Couchbase community edition chart
observIQ/charts pull request #43
Opened 2023-06-16 20:00 UTC by algchoo

* added chart to deploy a statefulset and service
* added readme with instructions on how to configure nodes and create a cluster

2023-06-16 20:12 UTC, jsirianni requested changes
Working well but I think the doc is missing a few details when deploying a new cluster.

2023-06-16 20:12 UTC, jsirianni commented on charts/couchbase-community/README.md
> +3. Using your browser of choice, visit `localhost:8091` and you will see the login page for the node. The username and password will be `Administrator:password` for all nodes.
I had to create a password here. The default username was filled in as `Administrator`

2023-06-16 20:12 UTC, jsirianni commented on charts/couchbase-community/README.md
> +4. After a successful login, go to the **Servers** page
Before this happens, I had to configure a "new cluster"

![Screenshot from 2023-06-16 16-11-51](https://github.com/observIQ/charts/assets/23043836/868c6062-3c6a-4eee-b575-c0132fae5435)

2023-06-19 17:32 UTC, algchoo commented
> Working well but I think the doc is missing a few details when deploying a new cluster.

Regarding the issues we we're seeing on your end, I was able to run this in k8s in various ways. Like you said, if it's working consistently for me, we should probably keep it.
* colima
* minikube using the docker driver
* minikube using the qemu2 driver

2023-06-19 17:43 UTC, jsirianni approved these changes

2023-06-19 18:14 UTC, merged